spring:
  application:
    name: Techcycle-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        - id: pontosdecoleta
#          uri: lb://PontosDeColeta
#          predicates:
#            - Path=/pontoscoleta/**
#
#        - id: marketplace
#          uri: lb://Marketplace
#          predicates:
#            - Path=/marketplace/**
#
#        - id: notificacao
#          uri: lb://Notificacao
#          predicates:
#            - Path=/notificacao/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8087
